require('./styles/usage/app.scss');
var common = require('./scripts/utils/util.common.js');
var home = require('./scripts/tpls/home.html');
var list = require('./scripts/tpls/list.html');
var my =require('./scripts/tpls/my.html');
var register=require('./scripts/tpls/register.html');
// require('./scripts/views/home.js');
// common.render(home);
common.render(register);
// require('./scripts/views/list.js');
require('./scripts/views/register.js');